#!/bin/bash
set -euxo pipefail

web_books_path=_pages/books.md
obsidian_books_path="$HOME/git/md-notes/Books.md"

cat > $web_books_path.tmp << EOF
---
layout: default
title: Books
order: 3
permalink: /books/
---
[//]: <> (Do not edit this file directly. It is generated using utils/update_books.sh)
EOF


# Ignore asterixed bullets and stuff after | 
cat "$obsidian_books_path" | head -n 3 >> $web_books_path.tmp
cat "$obsidian_books_path" | awk -F '|' '{print $2}' \
  | awk '{$1=$1};1' | grep -v '^-*$'| grep -v '.*\*$' \
  | grep -v '^Book$' | sed 's/^/- /g' >> $web_books_path.tmp 
mv $web_books_path.tmp $web_books_path
